# Generated by Django 6.0.3 on 2026-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('CONFIRMED', 'Confirmed'), ('PARTIAL', 'Partially Received'), ('RECEIVED', 'Received'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20),
        ),
    ]
