# Generated by Django 6.0.3 on 2026-05-28 09:47

from django.db import migrations, models


def backfill_amount_paid(apps, schema_editor):
    # POs already marked PAID under the old (non-cumulative) logic are fully
    # paid by definition — set amount_paid = total so record_payment's new
    # cumulative guard won't let them accept a bogus extra payment. PARTIAL
    # POs are left at 0: the old code never tracked how much was actually paid,
    # so the historical figure is unknowable and must be reconciled manually.
    PurchaseOrder = apps.get_model('stock', 'PurchaseOrder')
    PurchaseOrder.objects.filter(payment_status='PAID').update(
        amount_paid=models.F('total')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_normalize_canceled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.RunPython(backfill_amount_paid, migrations.RunPython.noop),
    ]
