# Generated by Django 6.0.3 on 2026-06-07 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_treasurytransaction_type'),
        ('stock', '0004_purchaseorder_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('type', models.CharField(choices=[('PURCHASE', 'Purchase (debt +)'), ('PAYMENT', 'Payment (debt -)'), ('RETURN', 'Return (debt -)'), ('ADJUSTMENT', 'Adjustment')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('source_account', models.CharField(blank=True, choices=[('SAFE', 'Safe'), ('BANK', 'Bank'), ('DRAWER', 'Shift drawer')], default='', max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note', models.TextField(blank=True, default='')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_transactions', to='base.user')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='stock.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
