# Generated by Django 6.0.3 on 2026-08-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_purchaseorderitem_quantity_canceled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceivingcorrection',
            name='supplier_balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceivingcorrection',
            name='supplier_balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
