# Generated by Django 6.0.3 on 2026-08-31 21:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def backfill_legacy_unfunded_payments(apps, schema_editor):
    PurchaseOrder = apps.get_model('stock', 'PurchaseOrder')
    SupplierPayment = apps.get_model('stock', 'SupplierPayment')
    SupplierPaymentAllocation = apps.get_model(
        'stock', 'SupplierPaymentAllocation',
    )
    SupplierTransaction = apps.get_model('stock', 'SupplierTransaction')

    legacy_rows = SupplierTransaction.objects.filter(
        type='PAYMENT', source_account='',
    ).order_by('id')
    for ledger in legacy_rows.iterator():
        payment = SupplierPayment.objects.create(
            branch_id=ledger.branch_id,
            supplier_id=ledger.supplier_id,
            principal_uzs=ledger.amount,
            fee_uzs=ledger.fee,
            total_debited_uzs=0,
            source_account='',
            allocation_mode='LEGACY_UNFUNDED',
            status='LEGACY_UNFUNDED',
            supplier_balance_before_uzs=ledger.balance_before,
            supplier_balance_after_uzs=ledger.balance_after,
            supplier_transaction_id=ledger.id,
            performed_by_id=ledger.performed_by_id,
            note=ledger.note,
            paid_at=ledger.created_at,
        )
        SupplierPayment.objects.filter(pk=payment.pk).update(
            created_at=ledger.created_at,
            updated_at=ledger.created_at,
        )
        if ledger.reference_type != 'PurchaseOrder' or ledger.reference_id is None:
            continue
        po = PurchaseOrder.objects.filter(
            pk=ledger.reference_id,
            supplier_id=ledger.supplier_id,
        ).first()
        if po is None:
            continue
        remaining = max(po.total - po.amount_paid, 0)
        SupplierPaymentAllocation.objects.create(
            payment_id=payment.id,
            purchase_order_id=po.id,
            amount_uzs=ledger.amount,
            payment_status_snapshot=po.payment_status,
            remaining_uzs_snapshot=remaining,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_money_control_foundation'),
        ('stock', '0012_purchasereceivingcorrection_supplier_balance_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('branch_id', models.CharField(db_index=True, max_length=50)),
                ('principal_uzs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_debited_uzs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source_account', models.CharField(blank=True, choices=[('SAFE', 'Safe'), ('BANK', 'Bank')], default='', max_length=10)),
                ('allocation_mode', models.CharField(choices=[('EXPLICIT', 'Explicit'), ('AUTO_OLDEST_DUE', 'Auto oldest due'), ('LEGACY_UNFUNDED', 'Legacy unfunded')], max_length=20)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('LEGACY_UNFUNDED', 'Legacy unfunded'), ('REVERSED', 'Reversed')], max_length=20)),
                ('supplier_balance_before_uzs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('supplier_balance_after_uzs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source_balance_before_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_balance_after_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_action_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('request_hash', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('actor_display_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status_snapshot', models.CharField(max_length=20)),
                ('remaining_uzs_snapshot', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['purchase_order_id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['branch_id', 'supplier', 'payment_due_date', 'payment_status'], name='stock_purch_branch__634fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['branch_id', 'is_active', 'item_type', 'category'], name='stock_stock_branch__30c14e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['branch_id', 'location', 'stock_item'], name='stock_stock_branch__621671_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['branch_id', 'currency', 'current_balance'], name='stock_suppl_branch__4516bb_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliertransaction',
            index=models.Index(fields=['supplier', 'type', 'created_at'], name='stock_suppl_supplie_a9e344_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliertransaction',
            index=models.Index(fields=['branch_id', 'reference_type', 'reference_id'], name='stock_suppl_branch__4ecd04_idx'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='base.user'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_supplier_payments', to='base.user'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='stock.supplier'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier_reversal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_reversal', to='stock.suppliertransaction'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment', to='stock.suppliertransaction'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='treasury_reversal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_reversal', to='base.treasurytransaction'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='treasury_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment', to='base.treasurytransaction'),
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='stock.supplierpayment'),
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='stock.purchaseorder'),
        ),
        migrations.RunPython(
            backfill_legacy_unfunded_payments,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['branch_id', 'supplier', 'paid_at'], name='stock_suppl_branch__9197ad_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['status', 'paid_at'], name='stock_suppl_status_b10d54_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'purchase_order'), name='uniq_supplier_payment_purchase_order'),
        ),
    ]
