# Generated by Django 6.0.3 on 2026-08-31 22:21

import django.db.models.deletion
from django.db import migrations, models


def backfill_receiving_posting_evidence(apps, schema_editor):
    PurchaseReceiving = apps.get_model('stock', 'PurchaseReceiving')
    SupplierTransaction = apps.get_model('stock', 'SupplierTransaction')
    for receiving in PurchaseReceiving.objects.filter(status='COMPLETED').iterator():
        value = sum(
            (
                item.quantity_received * item.unit_cost
                for item in receiving.items.filter(quality_status='PASSED')
            ),
            0,
        )
        matches = list(SupplierTransaction.objects.filter(
            type='PURCHASE',
            reference_type='PurchaseReceiving',
            reference_id=receiving.id,
            supplier_id=receiving.purchase_order.supplier_id,
            amount=value,
        ).order_by('id').values_list('id', flat=True)[:2])
        updates = {
            'received_value_uzs': value,
            'quality_posting_policy': 'PASSED_ONLY_PENDING_BLOCKS_COMPLETION',
        }
        if len(matches) == 1:
            updates['supplier_transaction_id'] = matches[0]
        PurchaseReceiving.objects.filter(pk=receiving.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_money_control_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceiving',
            name='completion_action_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchasereceiving',
            name='completion_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='purchasereceiving',
            name='quality_posting_policy',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='purchasereceiving',
            name='received_value_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceiving',
            name='supplier_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receiving', to='stock.suppliertransaction'),
        ),
        migrations.RunPython(
            backfill_receiving_posting_evidence,
            migrations.RunPython.noop,
        ),
    ]
