# Generated by Django 6.0.3 on 2026-08-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_purchasereceiving_completion_action_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='reversal_action_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reversal_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reversed_actor_display_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase (debt +)'), ('PAYMENT', 'Payment (debt -)'), ('PAYMENT_REVERSAL', 'Payment reversal (debt +)'), ('RETURN', 'Return (debt -)'), ('ADJUSTMENT', 'Adjustment')], max_length=20),
        ),
    ]
