# Generated by Django 6.0.3 on 2026-09-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_supplierpayment_reversal_action_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceivingitem',
            name='base_quantity',
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True,
            ),
        ),
        migrations.AddField(
            model_name='purchasereceivingitem',
            name='base_unit',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='stock.stockunit',
            ),
        ),
        migrations.AddField(
            model_name='purchasereceivingitem',
            name='base_unit_cost',
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True,
            ),
        ),
        migrations.AddField(
            model_name='purchasereceivingitem',
            name='conversion_to_base_snapshot',
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=15, null=True,
            ),
        ),
    ]
