# Generated by Django 6.0.3 on 2026-09-07 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0065_direct_supplier_invoices"),
        ("stock", "0017_secure_stock_adjustments"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_ORDER", "Planned purchase order"),
                    ("DIRECT_INVOICE", "Direct supplier invoice"),
                ],
                db_index=True,
                default="PURCHASE_ORDER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="invoice_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posted_supplier_invoices",
                to="base.user",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="posting_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacements",
                to="stock.purchasereceiving",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="reversal_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="reversal_reason",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="reversed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_supplier_invoices",
                to="base.user",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_ORDER", "Planned purchase order"),
                    ("DIRECT_INVOICE", "Direct supplier invoice"),
                ],
                db_index=True,
                default="PURCHASE_ORDER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="stock.supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="supplier_invoice_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="purchasereceiving",
            name="supplier_invoice_number_normalized",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="purchasereceivingitem",
            name="free_reason",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="purchasereceivingitem",
            name="invoice_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="purchasereceivingitem",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchasereceivingitem",
            name="line_total_uzs",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchasereceivingitem",
            name="stock_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_line",
                to="stock.stocktransaction",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceivingitem",
            name="supplier_stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_lines",
                to="stock.supplierstockitem",
            ),
        ),
        migrations.AddField(
            model_name="supplierstockitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="supplierstockitem",
            name="price_is_known",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supplierstockitem",
            name="price_source",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="supplierstockitem",
            name="price_source_invoice_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suppliertransaction",
            name="invoice_posting_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="purchasereceiving",
            index=models.Index(
                fields=["branch_id", "source_type", "invoice_date"],
                name="stock_purch_branch__052b75_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereceiving",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source_type", "DIRECT_INVOICE"),
                    models.Q(("supplier_invoice_number_normalized", ""), _negated=True),
                ),
                fields=("branch_id", "supplier", "supplier_invoice_number_normalized"),
                name="uniq_direct_supplier_invoice_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliertransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(invoice_posting_id__isnull=False),
                fields=("branch_id", "reference_type", "reference_id", "type"),
                name="uniq_supplier_invoice_ledger_reference",
            ),
        ),
    ]
