# Generated by Django 6.0.3 on 2026-09-07 16:34

import django.db.models.deletion
from django.db import migrations, models


def grant_opening_permission(apps, schema_editor):
    db = schema_editor.connection.alias
    key = "stock.supplier.opening.manage"
    Role = apps.get_model("base", "RolePermission")
    User = apps.get_model("base", "User")
    for model, rows in (
        (Role, Role.objects.using(db).filter(role="MANAGER")),
        (User, User.objects.using(db).filter(role="MANAGER", is_deleted=False)),
    ):
        for row in rows.iterator():
            current = row.permissions if isinstance(row.permissions, list) else []
            if key in current:
                continue
            changes = {"permissions": [*current, key]}
            if model == User:
                changes.update(
                    sync_version=models.F("sync_version") + 1, synced_at=None
                )
            model.objects.using(db).filter(pk=row.pk).update(**changes)


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0065_direct_supplier_invoices"),
        ("stock", "0019_direct_invoice_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpaymentallocation",
            name="opening_balance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opening_payment_allocations",
                to="stock.suppliertransaction",
            ),
        ),
        migrations.AddField(
            model_name="suppliertransaction",
            name="opening_balance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suppliertransaction",
            name="opening_balance_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="supplierpaymentallocation",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_allocations",
                to="stock.purchaseorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpaymentallocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "opening_balance"),
                name="uniq_supplier_payment_opening_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpaymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("opening_balance__isnull", True),
                        ("purchase_order__isnull", False),
                    ),
                    models.Q(
                        ("opening_balance__isnull", False),
                        ("purchase_order__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="supplier_allocation_one_debt_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliertransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_type", "SupplierOpeningBalance")),
                fields=("supplier",),
                name="uniq_supplier_opening_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliertransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reference_type", "SupplierOpeningBalance"), _negated=True
                    ),
                    models.Q(
                        ("opening_balance_date__isnull", False),
                        ("type", "ADJUSTMENT"),
                        models.Q(("opening_balance_manifest", {}), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="supplier_opening_balance_has_evidence",
            ),
        ),
        # Schema and additive permissions only: existing balances/history are untouched.
        migrations.RunPython(grant_opening_permission, migrations.RunPython.noop),
    ]
