# Generated by Django 6.0.3 on 2026-06-05 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0018_product_ikpu_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('SALE', 'Sale'), ('REFUND', 'Refund')], default='SALE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=10)),
                ('provider', models.CharField(default='', max_length=40)),
                ('mode', models.CharField(default='', max_length=10)),
                ('fiscal_sign', models.CharField(blank=True, max_length=64, null=True)),
                ('qr_url', models.TextField(blank=True, null=True)),
                ('fiscal_number', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('branch_id', models.CharField(db_index=True, default='', max_length=64)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscalized_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_receipts', to='base.order')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'receipt_type'], name='fiscalizati_status_ded4a7_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'receipt_type'), name='uniq_order_receipt_type')],
            },
        ),
    ]
