# Generated by Django 6.0.3 on 2026-08-28 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


PREPARATION_CATEGORIES = (
    'STAFF_SHORTAGE', 'HIGH_ORDER_VOLUME', 'EQUIPMENT_ISSUE',
    'KITCHEN_PROCESS', 'PRODUCT_COMPLEXITY', 'CASHIER_DELAY',
    'CUSTOMER_CHANGE', 'OTHER',
)


def seed_preparation_categories(apps, schema_editor):
    Category = apps.get_model('hr', 'PreparationAuditCategory')
    for code in PREPARATION_CATEGORIES:
        Category.objects.get_or_create(
            code=code, defaults={'name': code.replace('_', ' ').title()},
        )


def unseed_preparation_categories(apps, schema_editor):
    Category = apps.get_model('hr', 'PreparationAuditCategory')
    Category.objects.filter(code__in=PREPARATION_CATEGORIES).delete()


def backfill_attendance_minutes(apps, schema_editor):
    Attendance = apps.get_model('hr', 'Attendance')
    for row in Attendance.objects.filter(check_in__isnull=False, check_out__isnull=False).iterator():
        row.worked_minutes = max(0, int((row.check_out - row.check_in).total_seconds() // 60))
        row.overtime_minutes = max(0, int(float(row.overtime_hours or 0) * 60))
        row.save(update_fields=['worked_minutes', 'overtime_minutes'])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_rolepermission_role_alter_user_role'),
        ('hr', '0008_expensecategory_reporting_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationAuditCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_records', to='base.user'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_leave_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='grace_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scheduled_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='worked_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AttendanceExcuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical'), ('FAMILY', 'Family'), ('TRANSPORT', 'Transport'), ('APPROVED_LEAVE', 'Approved leave'), ('MANAGER_INSTRUCTION', 'Manager instruction'), ('OTHER', 'Other')], max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('excused_late_minutes', models.PositiveIntegerField(default=0)),
                ('excused_early_leave_minutes', models.PositiveIntegerField(default=0)),
                ('excused_absence_minutes', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excuses', to='hr.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_excuses', to='hr.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_attendance_excuses', to='base.user')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_attendance_excuses', to='base.user')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('CONDUCT', 'Conduct'), ('QUALITY', 'Quality'), ('PREPARATION_TIME', 'Preparation time'), ('OTHER', 'Other')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('default_amount_uzs', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('requires_evidence', models.BooleanField(default=True)),
                ('requires_comment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.user')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.user')),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('scheduled_start_local', models.TimeField()),
                ('scheduled_end_local', models.TimeField()),
                ('is_overnight', models.BooleanField(default=False)),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_schedules', to='base.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='hr.employee')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_work_schedules', to='base.user')),
            ],
            options={
                'ordering': ['employee_id', 'weekday', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='OperationalAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=60)),
                ('entity_id', models.PositiveBigIntegerField(db_index=True)),
                ('action', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('previous_state', models.CharField(blank=True, default='', max_length=40)),
                ('new_state', models.CharField(blank=True, default='', max_length=40)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.user')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('created_at_snapshot', models.DateTimeField()),
                ('ready_at_snapshot', models.DateTimeField()),
                ('elapsed_seconds', models.PositiveIntegerField()),
                ('target_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('target_name_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('performance_status', models.CharField(choices=[('ON_TIME', 'On time'), ('SLIGHTLY_LATE', 'Slightly late'), ('VERY_LATE', 'Very late'), ('UNTRACKED', 'Untracked')], max_length=20)),
                ('review_required', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('EXCUSED', 'Excused')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, default='')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_audit', to='base.order')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.user')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.user')),
            ],
            options={
                'ordering': ['-ready_at_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('business_date', models.DateField(db_index=True)),
                ('rule_code_snapshot', models.CharField(max_length=50)),
                ('rule_title_snapshot', models.CharField(max_length=200)),
                ('rule_category_snapshot', models.CharField(max_length=24)),
                ('rule_amount_snapshot_uzs', models.PositiveBigIntegerField(default=0)),
                ('amount_uzs', models.PositiveBigIntegerField(default=0)),
                ('evidence', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('excuse_text', models.TextField(blank=True, default='')),
                ('excuse_review_state', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('EXCUSED', 'Excused'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VOIDED', 'Voided'), ('APPROVED_PENDING_PAYROLL', 'Approved pending payroll')], default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('void_reason', models.TextField(blank=True, default='')),
                ('payroll_period_year', models.PositiveIntegerField(blank=True, null=True)),
                ('payroll_period_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_cases', to='hr.attendance')),
                ('attendance_excuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_cases', to='hr.attendanceexcuse')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_disciplinary_cases', to='base.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_cases', to='hr.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_disciplinary_cases', to='base.user')),
                ('salary_deduction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_case', to='hr.salarydeduction')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='hr.disciplinaryrule')),
                ('preparation_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_cases', to='hr.preparationaudit')),
            ],
            options={
                'ordering': ['-business_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreparationAuditPeriodClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationAuditReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='hr.preparationauditcategory')),
                ('linked_disciplinary_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparation_reviews', to='hr.disciplinarycase')),
                ('preparation_audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='hr.preparationaudit')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.user')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparation_audit_reviews', to='hr.employee')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_audit_reviews', to='base.user')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('original_check_in', models.DateTimeField(blank=True, null=True)),
                ('original_check_out', models.DateTimeField(blank=True, null=True)),
                ('requested_check_in', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out', models.DateTimeField(blank=True, null=True)),
                ('reason_category', models.CharField(choices=[('MISSING_ENTRY', 'Missing entry'), ('DEVICE_FAILURE', 'Device failure'), ('MANAGER_INSTRUCTION', 'Manager instruction'), ('DATA_ENTRY_ERROR', 'Data entry error'), ('OTHER', 'Other')], max_length=24)),
                ('reason_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_requests', to='hr.attendance')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_adjustment_requests', to='base.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_attendance_adjustments', to='base.user')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('attendance',), name='uniq_pending_attendance_adjustment')],
            },
        ),
        migrations.AddConstraint(
            model_name='disciplinaryrule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='discipline_rule_effective_range_valid'),
        ),
        migrations.AddIndex(
            model_name='employeeworkschedule',
            index=models.Index(fields=['employee', 'weekday', 'effective_from', 'effective_to'], name='hr_employee_employe_40ec55_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeworkschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='schedule_weekday_0_6'),
        ),
        migrations.AddConstraint(
            model_name='employeeworkschedule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='schedule_effective_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeeworkschedule',
            constraint=models.UniqueConstraint(fields=('employee', 'weekday', 'effective_from'), name='uniq_employee_schedule_effective_start'),
        ),
        migrations.AddIndex(
            model_name='operationalauditevent',
            index=models.Index(fields=['entity_type', 'entity_id', 'occurred_at'], name='hr_operatio_entity__32a191_idx'),
        ),
        migrations.AddIndex(
            model_name='preparationaudit',
            index=models.Index(fields=['branch_id', 'ready_at_snapshot'], name='hr_preparat_branch__30efe1_idx'),
        ),
        migrations.AddIndex(
            model_name='preparationaudit',
            index=models.Index(fields=['performance_status', 'review_status'], name='hr_preparat_perform_a5681e_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['employee', 'business_date', 'status'], name='hr_discipli_employe_567bfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='preparationauditperiodclose',
            constraint=models.UniqueConstraint(fields=('branch_id', 'period_start', 'period_end'), name='uniq_preparation_audit_period_close'),
        ),
        migrations.AddConstraint(
            model_name='preparationauditreview',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('preparation_audit',), name='uniq_current_preparation_audit_review'),
        ),
        migrations.RunPython(seed_preparation_categories, unseed_preparation_categories),
        migrations.RunPython(backfill_attendance_minutes, migrations.RunPython.noop),
    ]
