# Generated by Django 6.0.3 on 2026-08-31 21:15

import django.db.models.deletion
import hr.models
import uuid
from django.db import migrations, models


def backfill_expense_contract(apps, schema_editor):
    ExpenseCategory = apps.get_model('hr', 'ExpenseCategory')
    Expense = apps.get_model('hr', 'Expense')
    ExpenseTransition = apps.get_model('hr', 'ExpenseTransition')

    for category in ExpenseCategory.objects.all().order_by('id').iterator():
        ExpenseCategory.objects.filter(pk=category.pk).update(
            code=f'LEGACY_HR_{category.pk}',
        )

    transitions = []
    for expense in Expense.objects.select_related('category').iterator():
        category = expense.category
        updates = {
            'category_code_snapshot': category.code if category else '',
            'category_name_snapshot': category.name if category else '',
        }
        if expense.status in {'APPROVED', 'PAID'}:
            updates['approved_at'] = expense.updated_at
        if expense.status == 'REJECTED':
            updates['rejected_at'] = expense.updated_at
        if expense.status == 'PAID':
            updates['paid_at'] = expense.updated_at
        Expense.objects.filter(pk=expense.pk).update(**updates)
        actor_id = (
            expense.paid_by_id or expense.approved_by_id or expense.created_by_id
        )
        transitions.append(ExpenseTransition(
            expense_id=expense.pk,
            previous_status='',
            new_status=expense.status,
            actor_id=actor_id,
            branch_id=expense.branch_id,
            metadata={'legacy_migration': True},
        ))
    ExpenseTransition.objects.bulk_create(transitions, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_money_control_foundation'),
        ('hr', '0009_preparationauditcategory_attendance_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('previous_status', models.CharField(blank=True, default='', max_length=10)),
                ('new_status', models.CharField(max_length=10)),
                ('actor_display_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name_plural': 'expense categories'},
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expense',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_expenses', to='base.user'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='expense',
            name='category_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='fee_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='fee_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_action_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='requested_source',
            field=models.CharField(blank=True, choices=[('DRAWER', 'Shift drawer'), ('SAFE', 'Safe'), ('BANK', 'Bank')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='base.shift'),
        ),
        migrations.AddField(
            model_name='expense',
            name='treasury_reversal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_void', to='base.treasurytransaction'),
        ),
        migrations.AddField(
            model_name='expense',
            name='treasury_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_payment', to='base.treasurytransaction'),
        ),
        migrations.AddField(
            model_name='expense',
            name='void_action_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='void_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expense',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_expenses', to='base.user'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='allowed_sources',
            field=models.JSONField(blank=True, default=hr.models._default_expense_sources),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_categories', to='base.user'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='requires_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='requires_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expense_categories', to='base.user'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('VOIDED', 'Voided')], default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch_id', 'status', 'expense_date'], name='hr_expense_branch__038490_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch_id', 'category', 'paid_at'], name='hr_expense_branch__0416d8_idx'),
        ),
        migrations.AddField(
            model_name='expensetransition',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_transitions', to='base.user'),
        ),
        migrations.AddField(
            model_name='expensetransition',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='hr.expense'),
        ),
        migrations.RunPython(
            backfill_expense_contract,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='expensetransition',
            index=models.Index(fields=['expense', 'created_at'], name='hr_expenset_expense_6d838c_idx'),
        ),
    ]
