# Generated by Django 6.0.3 on 2026-08-31 21:45

import django.db.models.deletion
from django.db import migrations, models


def backfill_category_source_snapshots(apps, schema_editor):
    Expense = apps.get_model('hr', 'Expense')
    for expense in Expense.objects.select_related('category').iterator():
        sources = list(expense.category.allowed_sources) if expense.category else []
        Expense.objects.filter(pk=expense.pk).update(
            category_allowed_sources_snapshot=sources,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_idempotencykey_scope'),
        ('hr', '0010_money_control_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category_allowed_sources_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expense',
            name='subject_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_requests_as_subject', to='base.user'),
        ),
        migrations.RunPython(
            backfill_category_source_snapshots,
            migrations.RunPython.noop,
        ),
    ]
