# Generated by Django 6.0.3 on 2026-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_encrypted', models.BinaryField(blank=True, null=True)),
                ('org_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('status', models.CharField(choices=[('UNREGISTERED', 'Unregistered'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('PERPETUAL_UNLOCK', 'Perpetual unlock')], default='UNREGISTERED', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_server_now', models.DateTimeField(blank=True, null=True)),
                ('last_message', models.TextField(blank=True, default='')),
                ('fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'license',
                'verbose_name_plural': 'license',
            },
        ),
        migrations.CreateModel(
            name='LicenseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SETUP_ATTEMPTED', 'Setup attempted'), ('SETUP_SUCCEEDED', 'Setup succeeded'), ('HEARTBEAT_OK', 'Heartbeat OK'), ('HEARTBEAT_FAILED', 'Heartbeat failed'), ('STATUS_CHANGED', 'Status changed'), ('BLOCKED', 'Request blocked by middleware'), ('UNLOCK_ACCEPTED', 'Perpetual unlock accepted'), ('UNLOCK_REJECTED', 'Perpetual unlock rejected')], db_index=True, max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
