# Generated by Django 6.0.3 on 2026-05-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_license_singleton_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='days_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='warn',
            field=models.BooleanField(default=False),
        ),
    ]
