# Generated by Django 6.0.3 on 2026-05-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_license_balance_license_days_remaining_license_warn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('UNREGISTERED', 'Unregistered'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='UNREGISTERED', max_length=20),
        ),
        migrations.AlterField(
            model_name='licenseevent',
            name='action',
            field=models.CharField(choices=[('SETUP_ATTEMPTED', 'Setup attempted'), ('SETUP_SUCCEEDED', 'Setup succeeded'), ('HEARTBEAT_OK', 'Heartbeat OK'), ('HEARTBEAT_FAILED', 'Heartbeat failed'), ('STATUS_CHANGED', 'Status changed'), ('BLOCKED', 'Request blocked by middleware')], db_index=True, max_length=32),
        ),
    ]
