# Generated by Django 6.0.3 on 2026-05-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_shifttemplate_category_parent_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], db_index=True, default='OPEN', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='ip_address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='session',
            name='payload',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['payload'], name='base_sessio_payload_59bb3a_idx'),
        ),
    ]
