# Generated by Django 6.0.3 on 2026-05-11 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_normalize_order_status_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('action', models.CharField(choices=[('INKASSA_PERFORM', 'Inkassa performed'), ('USER_DELETE', 'User deleted'), ('SHIFT_RECONCILE', 'Shift reconciled'), ('ORDER_CANCEL', 'Order canceled')], db_index=True, max_length=32)),
                ('target_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('target_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to='base.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
