# Generated by Django 6.0.3 on 2026-05-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('response_status', models.PositiveSmallIntegerField(default=0)),
                ('response_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'idempotency_key',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='uniq_idempotency_scope_key')],
            },
        ),
    ]
