# Generated by Django 6.0.3 on 2026-05-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_idempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
