# Generated by Django 6.0.3 on 2026-05-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_session_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayIdCounter',
            fields=[
                ('scope', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'display_id_counter',
            },
        ),
    ]
