# Generated by Django 6.0.3 on 2026-05-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UZCARD', 'Uzcard'), ('HUMO', 'Humo'), ('PAYME', 'Payme')], db_index=True, max_length=10, null=True),
        ),
    ]
