# Generated by Django 6.0.3 on 2026-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('INKASSA_PERFORM', 'Inkassa performed'), ('USER_CREATE', 'User created'), ('USER_UPDATE', 'User updated'), ('USER_DELETE', 'User deleted'), ('SHIFT_RECONCILE', 'Shift reconciled'), ('ORDER_CANCEL', 'Order canceled'), ('PRODUCT_PRICE_CHANGE', 'Product price changed'), ('DISCOUNT_CREATE', 'Discount created'), ('DISCOUNT_UPDATE', 'Discount updated'), ('DISCOUNT_DELETE', 'Discount deleted'), ('LOYALTY_REDEEM', 'Loyalty stamps redeemed')], db_index=True, max_length=32),
        ),
    ]
