# Generated by Django 6.0.3 on 2026-06-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_sequencecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ikpu_code',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
    ]
