# Generated by Django 6.0.3 on 2026-06-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_product_ikpu_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('CASHIER', 'Cashier'), ('MANAGER', 'Manager'), ('WAITER', 'Waiter')], default='USER', max_length=10),
        ),
    ]
