# Generated by Django 6.0.3 on 2026-06-06 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('CASH', 'Cash'), ('UZCARD', 'Uzcard'), ('HUMO', 'Humo'), ('PAYME', 'Payme'), ('MIXED', 'Mixed')], max_length=10, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('icon', models.TextField(blank=True, default='', help_text='Inline SVG (24x24, currentColor)')),
                ('color', models.CharField(default='#3b82f6', max_length=9)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_method_config',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UZCARD', 'Uzcard'), ('HUMO', 'Humo'), ('PAYME', 'Payme'), ('MIXED', 'Mixed')], db_index=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('UZCARD', 'Uzcard'), ('HUMO', 'Humo'), ('PAYME', 'Payme'), ('MIXED', 'Mixed')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='base.order')),
            ],
            options={
                'db_table': 'order_payment',
                'indexes': [models.Index(fields=['order', 'method'], name='order_payme_order_i_ab248f_idx')],
            },
        ),
    ]
