# Generated by Django 6.0.3 on 2026-06-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_seed_payment_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('CASHIER', 'Cashier'), ('MANAGER', 'Manager'), ('WAITER', 'Waiter')], max_length=20, unique=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_permission',
            },
        ),
    ]
