# Generated by Django 6.0.3 on 2026-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_instant',
            field=models.BooleanField(default=False),
        ),
    ]
