# Generated by Django 6.0.3 on 2026-06-06 20:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_product_is_instant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('kind', models.CharField(choices=[('SAFE', 'Safe (cash)'), ('BANK', 'Bank (cards)')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('INKASSA_PERFORM', 'Inkassa performed'), ('USER_CREATE', 'User created'), ('USER_UPDATE', 'User updated'), ('USER_DELETE', 'User deleted'), ('SHIFT_RECONCILE', 'Shift reconciled'), ('ORDER_CANCEL', 'Order canceled'), ('PRODUCT_PRICE_CHANGE', 'Product price changed'), ('DISCOUNT_CREATE', 'Discount created'), ('DISCOUNT_UPDATE', 'Discount updated'), ('DISCOUNT_DELETE', 'Discount deleted'), ('LOYALTY_REDEEM', 'Loyalty stamps redeemed'), ('TREASURY_TRANSFER', 'Treasury transfer'), ('TREASURY_EXPENSE', 'Treasury expense')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('type', models.CharField(choices=[('INKASSA', 'Inkassa deposit'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('FEE', 'Transfer fee'), ('EXPENSE', 'Expense'), ('ADJUSTMENT', 'Adjustment')], max_length=15)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='base.treasuryaccount')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_transactions', to='base.treasuryaccount')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_transactions', to='base.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
