# Generated by Django 6.0.3 on 2026-06-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_treasuryaccount_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=12),
        ),
    ]
