# Generated by Django 6.0.3 on 2026-06-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_shift_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sync_state',
            },
        ),
    ]
