# Generated by Django 6.0.3 on 2026-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_table_unique_together_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurytransaction',
            name='type',
            field=models.CharField(choices=[('INKASSA', 'Inkassa deposit'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('FEE', 'Transfer fee'), ('EXPENSE', 'Expense'), ('ADJUSTMENT', 'Adjustment'), ('SUPPLIER_PAYMENT', 'Supplier payment'), ('SALARY_PAYMENT', 'Salary payment'), ('SHIFT_DEPOSIT', 'Shift settlement deposit')], max_length=20),
        ),
    ]
