# Generated by Django 6.0.3 on 2026-06-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_treasurytransaction_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_category_slug_active',
        ),
        migrations.RemoveConstraint(
            model_name='table',
            name='uniq_table_place_number_active',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='uniq_user_email_active',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('slug', ''), _negated=True)), fields=('slug',), name='uniq_category_slug_active'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('number', ''), _negated=True)), fields=('place', 'number'), name='uniq_table_place_number_active'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='uniq_user_email_active'),
        ),
    ]
