# Generated by Django 6.0.3 on 2026-06-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_category_uniq_category_slug_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefQueueCounter',
            fields=[
                ('scope', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chef_queue_counter',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='chef_queue_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
