# Generated by Django 6.0.3 on 2026-07-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_appsettings_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UZCARD', 'Uzcard'), ('HUMO', 'Humo'), ('CARD', 'Card'), ('PAYME', 'Payme'), ('MIXED', 'Mixed')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UZCARD', 'Uzcard'), ('HUMO', 'Humo'), ('CARD', 'Card'), ('PAYME', 'Payme'), ('MIXED', 'Mixed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='code',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UZCARD', 'Uzcard'), ('HUMO', 'Humo'), ('CARD', 'Card'), ('PAYME', 'Payme'), ('MIXED', 'Mixed')], max_length=10, unique=True),
        ),
    ]
