# Generated by Django 6.0.3 on 2026-07-13 19:40

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.db import migrations, models
from django.db.models import Q


CARD_METHODS = {'UZCARD', 'HUMO', 'CARD'}


def backfill_legacy_paid_cancellations(apps, schema_editor):
    """Materialize the accounting event old code represented only by status.

    Old cancellation already debited the drawer, so this migration records
    evidence only; it must not touch CashRegister.  AuditLog is the best known
    cancellation timestamp.  Where a legacy row has no audit entry, updated_at
    is the least-bad available event time (never rewrite paid_at itself).
    """
    Order = apps.get_model('base', 'Order')
    OrderPayment = apps.get_model('base', 'OrderPayment')
    OrderRefund = apps.get_model('base', 'OrderRefund')
    AuditLog = apps.get_model('base', 'AuditLog')
    Shift = apps.get_model('base', 'Shift')

    orders = Order.objects.filter(
        is_deleted=False, is_paid=True, status='CANCELED',
    ).iterator(chunk_size=500)
    for order in orders:
        if OrderRefund.objects.filter(
            order_id=order.id, source='ORDER_CANCEL',
        ).exists():
            continue

        audit = (
            AuditLog.objects.filter(
                action='ORDER_CANCEL', target_type='Order', target_id=order.id,
            )
            .order_by('-created_at', '-pk')
            .first()
        )
        refunded_at = (
            audit.created_at if audit else
            (order.updated_at or order.paid_at or order.created_at)
        )
        cashier_id = (audit.actor_id if audit and audit.actor_id else order.cashier_id)
        shift = None
        if cashier_id and refunded_at:
            shift = (
                Shift.objects.filter(
                    user_id=cashier_id,
                    is_deleted=False,
                    start_time__lte=refunded_at,
                )
                .filter(Q(end_time__isnull=True) | Q(end_time__gte=refunded_at))
                .order_by('-start_time', '-pk')
                .first()
            )

        total = Decimal(order.total_amount or 0)
        rows = list(
            OrderPayment.objects.filter(order_id=order.id, is_deleted=False)
            .values_list('method', 'amount')
        )
        courier_rows = []
        # The reusable core has no dependency on the optional couriers app.
        # On the server, however, include any still-PAID door collection so it
        # is classified as provider cash/non-cash rather than drawer cash.
        connection = schema_editor.connection
        if 'couriers_courierpayment' in connection.introspection.table_names():
            with connection.cursor() as cursor:
                cursor.execute(
                    'SELECT provider, amount FROM couriers_courierpayment '
                    'WHERE order_id = %s AND status = %s',
                    [order.id, 'PAID'],
                )
                courier_rows = [
                    ({'CASH': 'CASH', 'CARD': 'UZCARD', 'QR': 'PAYME'}.get(
                        provider, provider,
                    ), amount)
                    for provider, amount in cursor.fetchall()
                ]
        cash = card = payme = unknown = Decimal('0.00')
        drawer_cash = Decimal('0.00')
        card_detail = {'UZCARD': '0.00', 'HUMO': '0.00', 'CARD': '0.00'}
        if rows or courier_rows:
            noncash = Decimal('0.00')
            all_cash_tendered = Decimal('0.00')
            drawer_cash_tendered = Decimal('0.00')
            drawer_noncash = Decimal('0.00')
            courier_collected = Decimal('0.00')
            invalid = False
            for source, payment_rows in (
                ('drawer', rows), ('courier', courier_rows),
            ):
                for method, raw_amount in payment_rows:
                    method = (method or 'CASH').strip().upper()
                    amount = Decimal(raw_amount or 0)
                    if source == 'courier':
                        courier_collected += max(amount, Decimal('0'))
                    if method in CARD_METHODS:
                        card += amount
                        noncash += amount
                        if source == 'drawer':
                            drawer_noncash += amount
                        card_detail[method] = str(
                            Decimal(card_detail[method]) + amount
                        )
                    elif method == 'PAYME':
                        payme += amount
                        noncash += amount
                        if source == 'drawer':
                            drawer_noncash += amount
                    elif method == 'CASH':
                        all_cash_tendered += amount
                        if source == 'drawer':
                            drawer_cash_tendered += amount
                    else:
                        invalid = True
            residual_cash = total - noncash
            if (invalid or noncash > total
                    or all_cash_tendered < max(residual_cash, Decimal('0'))):
                cash = card = payme = Decimal('0.00')
                unknown = total
                drawer_cash = Decimal('0.00')
                card_detail = {'UZCARD': '0.00', 'HUMO': '0.00', 'CARD': '0.00'}
            else:
                cash = residual_cash
                drawer_bill_residual = max(
                    total - drawer_noncash - courier_collected,
                    Decimal('0'),
                )
                drawer_cash = min(
                    cash, drawer_cash_tendered, drawer_bill_residual,
                )
        else:
            method = (order.payment_method or 'CASH').strip().upper()
            if method == 'CASH':
                cash = total
                drawer_cash = total
            elif method in CARD_METHODS:
                card = total
                card_detail[method] = str(total)
            elif method == 'PAYME':
                payme = total
            else:
                unknown = total

        OrderRefund.objects.create(
            order_id=order.id,
            shift_id=(shift.id if shift else None),
            cashier_id=(cashier_id if shift else None),
            amount=total,
            cash_amount=cash,
            drawer_cash_amount=drawer_cash,
            card_amount=card,
            payme_amount=payme,
            unknown_amount=unknown,
            card_detail=card_detail,
            refunded_at=refunded_at,
            source='ORDER_CANCEL',
            source_id=str(order.uuid),
            reason='Legacy paid cancellation (backfilled)',
            branch_id=order.branch_id,
            synced_at=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_inkassa_register_commands'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('drawer_cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payme_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unknown_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_detail', models.JSONField(blank=True, default=dict)),
                ('refunded_at', models.DateTimeField(db_index=True)),
                ('register_command', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('ORDER_CANCEL', 'Order cancellation'), ('COURIER_PAYMENT', 'Courier/provider payment')], max_length=32)),
                ('source_id', models.CharField(max_length=160)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_refunds', to='base.user')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', related_query_name='refund', to='base.order')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_refunds', to='base.shift')),
            ],
            options={
                'db_table': 'order_refund',
                'indexes': [models.Index(fields=['refunded_at', 'cashier'], name='order_refun_refunde_46813f_idx'), models.Index(fields=['branch_id', 'refunded_at'], name='order_refun_branch__ed0f07_idx')],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('cash_amount__gte', 0), ('drawer_cash_amount__gte', 0), ('card_amount__gte', 0), ('payme_amount__gte', 0), ('unknown_amount__gte', 0)), name='order_refund_amounts_nonnegative'),
                    models.CheckConstraint(condition=models.Q(('drawer_cash_amount__lte', models.F('cash_amount'))), name='order_refund_drawer_cash_lte_cash'),
                    models.CheckConstraint(condition=models.Q(('amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('cash_amount'), '+', models.F('card_amount')), '+', models.F('payme_amount')), '+', models.F('unknown_amount')))), name='order_refund_tenders_sum_amount'),
                    models.CheckConstraint(condition=models.Q(models.Q(('cashier__isnull', True), ('shift__isnull', True)), models.Q(('cashier__isnull', False), ('shift__isnull', False)), _connector='OR'), name='order_refund_shift_cashier_pair'),
                    models.CheckConstraint(condition=~models.Q(('source_id', '')), name='order_refund_source_id_required'),
                    models.UniqueConstraint(fields=('source', 'source_id'), name='uniq_order_refund_source_event'),
                    models.UniqueConstraint(condition=models.Q(('source', 'ORDER_CANCEL')), fields=('order',), name='uniq_order_cancel_refund'),
                ],
            },
        ),
        migrations.RunPython(
            backfill_legacy_paid_cancellations,
            migrations.RunPython.noop,
        ),
    ]
