# Generated by Django 6.0.3 on 2026-08-28 12:46

from django.db import migrations, models


WAREHOUSE_PERMISSIONS = [
    'stock.catalog.view', 'stock.level.view', 'stock.batch.view',
    'stock.supplier.view', 'stock.purchase.view', 'stock.receiving.create',
    'stock.receiving.update_draft', 'stock.receiving.complete',
    'stock.transfer.view', 'stock.transfer.create', 'stock.count.view',
    'stock.count.create', 'stock.count.record', 'stock.adjustment.request',
]


def seed_warehouse_role(apps, schema_editor):
    RolePermission = apps.get_model('base', 'RolePermission')
    RolePermission.objects.get_or_create(
        role='WAREHOUSE', defaults={'permissions': WAREHOUSE_PERMISSIONS},
    )


def unseed_warehouse_role(apps, schema_editor):
    RolePermission = apps.get_model('base', 'RolePermission')
    RolePermission.objects.filter(role='WAREHOUSE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_remove_exclusive_shift_device_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('CASHIER', 'Cashier'), ('MANAGER', 'Manager'), ('WAITER', 'Waiter'), ('COURIER', 'Courier'), ('WAREHOUSE', 'Warehouse'), ('CHEF', 'Chef')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('CASHIER', 'Cashier'), ('MANAGER', 'Manager'), ('WAITER', 'Waiter'), ('COURIER', 'Courier'), ('WAREHOUSE', 'Warehouse'), ('CHEF', 'Chef')], default='USER', max_length=10),
        ),
        migrations.RunPython(seed_warehouse_role, unseed_warehouse_role),
    ]
