# Generated by Django 6.0.3 on 2026-09-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_remove_exclusive_shift_device_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='waiter_payment_mode',
            field=models.CharField(choices=[('CASHIER_HANDOFF', 'Cashier collects payment'), ('PERMITTED_WAITER', 'Waiter with payment permission may collect')], default='CASHIER_HANDOFF', max_length=24),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='waiter_require_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='served_orders', to='base.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter_policy_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter_shift',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='served_orders', to='base.shift'),
        ),
    ]
