# Generated by Django 6.0.3 on 2026-08-31 21:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def prepare_money_control_foundation(apps, schema_editor):
    PaymentMethodConfig = apps.get_model('base', 'PaymentMethodConfig')
    TreasuryAccount = apps.get_model('base', 'TreasuryAccount')
    TreasuryTransaction = apps.get_model('base', 'TreasuryTransaction')

    PaymentMethodConfig.objects.filter(code='CASH').update(
        treasury_destination='SAFE',
    )
    PaymentMethodConfig.objects.filter(
        code__in=['CARD', 'UZCARD', 'HUMO', 'PAYME'],
    ).update(treasury_destination='BANK')

    for account in TreasuryAccount.objects.all().iterator():
        branches = list(
            TreasuryTransaction.objects.filter(account_id=account.id)
            .exclude(branch_id__in=['', 'cloud'])
            .order_by('branch_id')
            .values_list('branch_id', flat=True)
            .distinct()[:2]
        )
        if len(branches) == 1:
            TreasuryAccount.objects.filter(pk=account.pk).update(
                branch_id=branches[0],
            )

    for row in TreasuryTransaction.objects.select_related('performed_by').iterator():
        actor = row.performed_by
        snapshot = ''
        if actor is not None:
            snapshot = f'{actor.first_name} {actor.last_name}'.strip()
        TreasuryTransaction.objects.filter(pk=row.pk).update(
            actor_display_snapshot=snapshot,
            category_name_snapshot=row.category or '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_rolepermission_role_alter_user_role'),
        ('hr', '0009_preparationauditcategory_attendance_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='treasuryaccount',
            name='uniq_active_treasury_account_kind',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='shift_settlement_cutover_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='treasury_posting_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentmethodconfig',
            name='treasury_destination',
            field=models.CharField(blank=True, choices=[('SAFE', 'Safe'), ('BANK', 'Bank')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='actor_display_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='canonical_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_transactions', to='hr.expensecategory'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='category_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='category_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='command_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='base.treasurytransaction'),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='type',
            field=models.CharField(choices=[('INKASSA', 'Inkassa deposit'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('FEE', 'Transfer fee'), ('EXPENSE', 'Expense'), ('EXPENSE_REVERSAL', 'Expense reversal'), ('ADJUSTMENT', 'Adjustment'), ('SUPPLIER_PAYMENT', 'Supplier payment'), ('SUPPLIER_PAYMENT_REVERSAL', 'Supplier payment reversal'), ('SALARY_PAYMENT', 'Salary payment'), ('SHIFT_DEPOSIT', 'Shift settlement deposit'), ('SHIFT_RECLASS_OUT', 'Legacy shift reclass out'), ('SHIFT_RECLASS_IN', 'Legacy shift reclass in')], max_length=32),
        ),
        migrations.RunPython(
            prepare_money_control_foundation,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['account', 'type', 'created_at'], name='base_treasu_account_5c8fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['branch_id', 'reference_type', 'reference_id'], name='base_treasu_branch__7fedd0_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['canonical_category', 'created_at'], name='base_treasu_canonic_e705cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='treasuryaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch_id', 'kind'), name='uniq_active_treasury_account_branch_kind'),
        ),
        migrations.AddConstraint(
            model_name='treasurytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('command_id__isnull', False)), fields=('account', 'command_id', 'type'), name='uniq_treasury_command_account_type'),
        ),
        migrations.AddConstraint(
            model_name='treasurytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_type', 'LegacyShiftReclassification')), fields=('account', 'reference_id'), name='uniq_legacy_shift_reclass_account'),
        ),
    ]
