# Generated by Django 6.0.3 on 2026-08-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_money_control_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='scope',
            field=models.CharField(db_index=True, max_length=180),
        ),
    ]
