# Generated by Django 6.0.3 on 2026-08-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_money_control_permissions'),
        ('hr', '0012_backfill_legacy_treasury_expenses'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='treasurytransaction',
            name='uniq_treasury_command_account_type',
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='settlement_action_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='settlement_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='settlement_request_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='treasurytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('command_id__isnull', False)), fields=('account', 'command_id', 'type', 'category'), name='uniq_treasury_command_account_type'),
        ),
    ]
