# Generated by Django 6.0.3 on 2026-08-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_remove_treasurytransaction_uniq_treasury_command_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('INKASSA_PERFORM', 'Inkassa performed'), ('USER_CREATE', 'User created'), ('USER_UPDATE', 'User updated'), ('USER_DELETE', 'User deleted'), ('SHIFT_RECONCILE', 'Shift reconciled'), ('ORDER_CANCEL', 'Order canceled'), ('PRODUCT_PRICE_CHANGE', 'Product price changed'), ('DISCOUNT_CREATE', 'Discount created'), ('DISCOUNT_UPDATE', 'Discount updated'), ('DISCOUNT_DELETE', 'Discount deleted'), ('LOYALTY_REDEEM', 'Loyalty stamps redeemed'), ('TREASURY_TRANSFER', 'Treasury transfer'), ('TREASURY_EXPENSE', 'Treasury expense'), ('EXPENSE_CATEGORY_CREATE', 'Expense category created'), ('EXPENSE_CATEGORY_UPDATE', 'Expense category updated'), ('EXPENSE_CATEGORY_DEACTIVATE', 'Expense category deactivated'), ('SUPPLIER_PAYMENT', 'Supplier payment'), ('SUPPLIER_PAYMENT_REVERSE', 'Supplier payment reversed'), ('ORDER_PAYMENT_REPAIR', 'Order payment repaired'), ('FINANCIAL_REPAIR', 'Historical financial repair')], db_index=True, max_length=32),
        ),
    ]
