# Generated by Django 6.0.3 on 2026-08-31 21:16

import django.db.models.deletion
from django.utils import timezone
from django.db import migrations, models


def migrate_cashbox_expense_evidence(apps, schema_editor):
    CashboxExpense = apps.get_model('cashbox', 'CashboxExpense')
    CashboxExpenseCategory = apps.get_model(
        'cashbox', 'CashboxExpenseCategory',
    )
    Expense = apps.get_model('hr', 'Expense')
    ExpenseCategory = apps.get_model('hr', 'ExpenseCategory')
    ExpenseTransition = apps.get_model('hr', 'ExpenseTransition')

    category_map = {}
    for legacy in CashboxExpenseCategory.objects.all().order_by('id').iterator():
        canonical = ExpenseCategory.objects.create(
            code=f'MIGRATED_DRAWER_{legacy.pk}',
            name=f'[Migrated drawer] {legacy.name}',
            description=(
                f'Automatically isolated from legacy cashbox category '
                f'{legacy.pk}; review before merging.'
            ),
            reporting_group=legacy.reporting_group,
            is_active=legacy.is_active,
            sort_order=legacy.sort_order,
            allowed_sources=['DRAWER'],
            branch_id=legacy.branch_id,
        )
        CashboxExpenseCategory.objects.filter(pk=legacy.pk).update(
            canonical_category_id=canonical.pk,
        )
        category_map[legacy.pk] = canonical

    marker = '[ALPHAPOS_CASHBOX_COMMAND_V1]\n'
    rows = CashboxExpense.objects.filter(
        canonical_expense__isnull=True,
        recipient_supplier__isnull=True,
    ).order_by('id')
    for cashbox in rows.iterator():
        category = category_map.get(cashbox.category_id)
        comment = cashbox.comment or ''
        if comment.startswith(marker):
            comment = comment[len(marker):]
        occurred_at = cashbox.created_at
        expense = Expense.objects.create(
            category_id=category.pk if category else None,
            category_code_snapshot=category.code if category else '',
            category_name_snapshot=category.name if category else '',
            amount=cashbox.amount,
            description=comment,
            expense_date=timezone.localtime(occurred_at).date(),
            payment_method='CASH',
            status='PAID',
            requested_source='DRAWER',
            shift_id=cashbox.shift_id,
            fee_uzs=0,
            created_by_id=cashbox.created_by_id,
            paid_by_id=cashbox.created_by_id,
            paid_at=occurred_at,
            branch_id=cashbox.branch_id,
            notes='Migrated from legacy CashboxExpense evidence.',
        )
        Expense.objects.filter(pk=expense.pk).update(
            created_at=occurred_at,
            updated_at=occurred_at,
        )
        ExpenseTransition.objects.create(
            expense_id=expense.pk,
            previous_status='',
            new_status='PAID',
            actor_id=cashbox.created_by_id,
            branch_id=cashbox.branch_id,
            metadata={
                'legacy_cashbox_expense_id': cashbox.pk,
                'approval_evidence_missing': True,
            },
        )
        CashboxExpense.objects.filter(pk=cashbox.pk).update(
            canonical_category_id=category.pk if category else None,
            canonical_expense_id=expense.pk,
            category_code_snapshot=category.code if category else '',
            category_name_snapshot=category.name if category else '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0003_cashboxexpensecategory_reporting_group'),
        ('hr', '0010_money_control_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxexpense',
            name='canonical_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_expenses', to='hr.expensecategory'),
        ),
        migrations.AddField(
            model_name='cashboxexpense',
            name='canonical_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_payment', to='hr.expense'),
        ),
        migrations.AddField(
            model_name='cashboxexpense',
            name='category_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='cashboxexpense',
            name='category_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cashboxexpense',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='cashbox.cashboxexpense'),
        ),
        migrations.AddField(
            model_name='cashboxexpensecategory',
            name='canonical_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_cashbox_category', to='hr.expensecategory'),
        ),
        migrations.RunPython(
            migrate_cashbox_expense_evidence,
            migrations.RunPython.noop,
        ),
    ]
