# Generated by Django 6.0.3 on 2026-08-31 22:21

from django.db import migrations, models


def backfill_actor_snapshots(apps, schema_editor):
    CashboxExpense = apps.get_model('cashbox', 'CashboxExpense')
    for row in CashboxExpense.objects.select_related('created_by').iterator():
        actor = row.created_by
        name = '' if actor is None else f'{actor.first_name} {actor.last_name}'.strip()
        CashboxExpense.objects.filter(pk=row.pk).update(
            actor_display_snapshot=name,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_idempotencykey_scope'),
        ('cashbox', '0004_money_control_contract'),
        ('hr', '0011_expense_category_allowed_sources_snapshot_and_more'),
        ('stock', '0014_purchasereceiving_completion_action_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxexpense',
            name='actor_display_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cashboxexpense',
            name='command_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cashboxexpense',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='cashboxexpense',
            index=models.Index(fields=['branch_id', 'created_at'], name='cashbox_cas_branch__208c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboxexpense',
            index=models.Index(fields=['canonical_category', 'created_at'], name='cashbox_cas_canonic_5b667f_idx'),
        ),
        migrations.RunPython(backfill_actor_snapshots, migrations.RunPython.noop),
    ]
