# Generated by Django 6.0.3 on 2026-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Document the available {placeholders} for this template.'),
        ),
    ]
