# Generated by Django 6.0.3 on 2026-05-15 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_order_payment_method'),
        ('notifications', '0002_notificationtemplate_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('language_code', models.CharField(blank=True, default='', max_length=8)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_customers', to='base.user')),
            ],
            options={
                'verbose_name': 'telegram customer',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
