# Generated by Django 6.0.3 on 2026-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_telegramcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramcustomer',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
