# Generated by Django 6.0.3 on 2026-05-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_telegramcustomer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('stamps_balance', models.PositiveIntegerField(default=0)),
                ('stamps_earned_total', models.PositiveIntegerField(default=0)),
                ('stamps_redeemed_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'loyalty account',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('stamps_per_completed_order', models.PositiveIntegerField(default=1)),
                ('stamps_per_reward', models.PositiveIntegerField(default=10)),
                ('reward_description', models.CharField(default='Bepul ichimlik', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'loyalty settings',
                'verbose_name_plural': 'loyalty settings',
            },
        ),
        migrations.CreateModel(
            name='OrderLoyaltyCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_index=True, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('stamps_credited', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
