# Generated by Django 6.0.3 on 2026-05-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_cart_cartitem_cart_one_active_cart_per_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('stamps_spent', models.PositiveIntegerField()),
                ('order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cashier_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
