# Generated by Django 6.0.3 on 2026-06-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_loyaltyredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='chat_routing',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
